
package com.bizvision.esb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.spi.Provider;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IF_ServiceService", targetNamespace = "http://www.pgxxgc.com/IF_Service", wsdlLocation = "http://10.1.30.9:8080/WebServiceProject/services/IF_Service?wsdl")
public class IFServiceService extends Service {

	private final static URL IFSERVICESERVICE_WSDL_LOCATION;
	private final static WebServiceException IFSERVICESERVICE_EXCEPTION;
	private final static QName IFSERVICESERVICE_QNAME = new QName("http://www.pgxxgc.com/IF_Service",
			"IF_ServiceService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			// url = new URL("http://10.1.30.45:7080/services/IF_Service");
			 url = new URL("http://10.1.30.9:7080/services/IF_Service");
			// url = new
			// URL("http://10.1.30.9:8080/WebServiceProject/services/IF_Service?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		IFSERVICESERVICE_WSDL_LOCATION = url;
		IFSERVICESERVICE_EXCEPTION = e;
	}

	public IFServiceService() {
		super(__getWsdlLocation(), IFSERVICESERVICE_QNAME);
	}

	public IFServiceService(WebServiceFeature... features) {
		super(__getWsdlLocation(), IFSERVICESERVICE_QNAME, features);
	}

	public IFServiceService(URL wsdlLocation) {
		super(wsdlLocation, IFSERVICESERVICE_QNAME);
	}

	public IFServiceService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, IFSERVICESERVICE_QNAME, features);
	}

	public IFServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IFServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns IFService
	 */
	@WebEndpoint(name = "IF_Service")
	public IFService getIFService() {
		return super.getPort(new QName("http://www.pgxxgc.com/IF_Service", "IF_Service"), IFService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on
	 *            the proxy. Supported features not in the <code>features</code>
	 *            parameter will have their default values.
	 * @return returns IFService
	 */
	@WebEndpoint(name = "IF_Service")
	public IFService getIFService(WebServiceFeature... features) {
		return super.getPort(new QName("http://www.pgxxgc.com/IF_Service", "IF_Service"), IFService.class, features);
	}

	private static URL __getWsdlLocation() {
		if (IFSERVICESERVICE_EXCEPTION != null) {
			throw IFSERVICESERVICE_EXCEPTION;
		}
		return IFSERVICESERVICE_WSDL_LOCATION;
	}

}
