
package com.bizvision.esb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IF_Service", targetNamespace = "http://www.pgxxgc.com/IF_Service")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IFService {


    /**
     * 
     * @param sContent
     * @param sMsgID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IFService")
    @WebResult(name = "IFServiceReturn", targetNamespace = "http://www.pgxxgc.com/IF_Service")
    @RequestWrapper(localName = "IFService", targetNamespace = "http://www.pgxxgc.com/IF_Service", className = "com.bizvision.esb.IFService_Type")
    @ResponseWrapper(localName = "IFServiceResponse", targetNamespace = "http://www.pgxxgc.com/IF_Service", className = "com.bizvision.esb.IFServiceResponse")
    public String ifService(
        @WebParam(name = "sMsgID", targetNamespace = "http://www.pgxxgc.com/IF_Service")
        String sMsgID,
        @WebParam(name = "sContent", targetNamespace = "http://www.pgxxgc.com/IF_Service")
        String sContent);

}
